# Generated by Django 2.1.2 on 2018-10-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='docfile',
            field=models.TextField(blank=True),
        ),
    ]
