# Generated by Django 2.0.5 on 2018-11-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181029_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='docfile',
            field=models.BinaryField(),
        ),
    ]
