# Generated by Django 2.1.2 on 2018-11-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20181121_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='schema',
            field=models.CharField(default='AES', max_length=20),
        ),
    ]
